name: Build

on:
  pull_request:

jobs:
  test:
    name: Build check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore packages for solution
      run: dotnet restore

    - name: Build solution (NET Core)
      run: dotnet build --no-restore -c debug

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 4.7.2

    - name: Build solution (NET Framework)
      run: msbuild YourSolution.sln /p:Configuration=Release
